# Generated by Django 2.2.8 on 2020-04-10 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='black_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
