# Generated by Django 2.2.8 on 2020-04-16 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_black_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='black_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
