# Generated by Django 2.2.8 on 2020-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200416_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemessage',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
