# Generated by Django 2.2.8 on 2020-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_voicemessage_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicemessage',
            old_name='viewed',
            new_name='is_heard',
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
