# Generated by Django 2.2.8 on 2020-04-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200422_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemessage',
            name='extra_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='extra_type',
            field=models.CharField(choices=[('video', 'video'), ('photo', 'photo'), ('doc', 'doc')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
