# Generated by Django 2.2.8 on 2020-05-21 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200424_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemessage',
            name='extra_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='voicemessage',
            name='extra_type',
            field=models.CharField(choices=[('video', 'video'), ('image', 'image'), ('doc', 'doc')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voicemessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('photo', models.FileField(null=True, upload_to='')),
                ('access_key', models.CharField(blank=True, max_length=100, null=True)),
                ('general_access', models.BooleanField(default=True)),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='member_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='voicemessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.GroupMessage'),
        ),
    ]
