# Generated by Django 2.2.8 on 2020-08-03 17:14

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200522_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('recurrences', recurrence.fields.RecurrenceField()),
            ],
        ),
    ]
